# rig bashrc (base product shell)
if [ -n "${RIG_CONFIG:-}" ] && [ -f "$RIG_CONFIG/shell/common.sh" ]; then
  # shellcheck disable=SC1091
  . "$RIG_CONFIG/shell/common.sh"
elif [ -n "${RIG_ROOT:-}" ] && [ -f "$RIG_ROOT/templates/shell/common/profile.sh" ]; then
  # shellcheck disable=SC1091
  . "$RIG_ROOT/templates/shell/common/profile.sh"
fi

PS1='\u@\h:\w\$ '
