# Shared CLI baseline (macos)
# Used by both workstation and compute roles.
brew "bash"
brew "zsh"
brew "git"
brew "openssh"
brew "tmux"
brew "fzf"
brew "eza"
brew "bat"
brew "zoxide"
brew "rsync"
brew "tree"
brew "btop"
brew "fastfetch"
brew "tldr"
brew "gitleaks"
brew "thefuck"
brew "watch"
