# Workstation extras (GUI / full dev)
brew "gh"
brew "colima"
brew "docker"
brew "docker-compose"
brew "uv"
brew "pyenv"
brew "juliaup"
brew "cmake"
brew "ffmpeg"
brew "ollama"
brew "openjdk@17"
brew "r"
brew "rust"
brew "terminal-notifier"
brew "telnet"

cask "cursor"
cask "betterdisplay"
cask "stats"
# Optional personal apps — enable locally via overlay / host packages.add if desired:
# cask "discord"
# cask "dropbox"
# cask "visual-studio-code"
# cask "zotero"
# cask "quarto"
# cask "github"
# cask "emacs-app"
# cask "julide"
# cask "hot"
