use crate::error::{Result, RigError};
use crate::paths;
use crate::schema::Host;
use std::fs;
use std::path::{Path, PathBuf};

/// Generate SSH config text from registered hosts (+ optional header template).
pub fn generate(root: &Path, hosts: &[(PathBuf, Host)]) -> String {
    let mut out = String::new();
    let header = paths::templates_dir(root).join("ssh/config.header");
    if header.is_file() {
        if let Ok(h) = fs::read_to_string(&header) {
            out.push_str(h.trim_end());
            out.push_str("\n\n");
        }
    }
    out.push_str("# Generated by rig — do not edit by hand\n");
    out.push_str("# Source: hosts/*.toml [[ssh]] (or legacy vpn/lan/thunderbolt)\n\n");
    for (_, h) in hosts {
        let user = h.resolved_user();
        for path in h.ssh_paths() {
            push_host(&mut out, &path.alias, &path.ip, &user, path.link.comment());
        }
    }
    out
}

pub fn host_aliases(text: &str) -> Vec<String> {
    text.lines()
        .filter_map(|l| l.strip_prefix("Host "))
        .map(str::trim)
        .filter(|s| !s.is_empty() && !s.contains('*'))
        .map(str::to_string)
        .collect()
}

fn push_host(out: &mut String, alias: &str, ip: &str, user: &str, comment: &str) {
    out.push_str(&format!(
        "Host {alias}\n  # {comment}\n  HostName {ip}\n  User {user}\n\n"
    ));
}

pub fn ssh_dir() -> Result<PathBuf> {
    let home = std::env::var_os("HOME")
        .map(PathBuf::from)
        .ok_or_else(|| RigError::Msg("HOME is not set".into()))?;
    Ok(home.join(".ssh"))
}

/// Write generated config to ~/.ssh/config.d/rig.conf and ensure Include.
pub fn write_ssh_config(root: &Path, hosts: &[(PathBuf, Host)]) -> Result<PathBuf> {
    let ssh = ssh_dir()?;
    let config_d = ssh.join("config.d");
    fs::create_dir_all(&config_d).map_err(RigError::Io)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&ssh, fs::Permissions::from_mode(0o700));
        let _ = fs::set_permissions(&config_d, fs::Permissions::from_mode(0o700));
    }

    let dest = config_d.join("rig.conf");
    let text = generate(root, hosts);
    fs::write(&dest, &text).map_err(RigError::Io)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(&dest, fs::Permissions::from_mode(0o600));
    }

    ensure_include(&ssh.join("config"))?;
    Ok(dest)
}

const INCLUDE_LINE: &str = "Include config.d/*.conf";

fn ensure_include(config_path: &Path) -> Result<()> {
    let existing = if config_path.is_file() {
        fs::read_to_string(config_path).map_err(RigError::Io)?
    } else {
        String::new()
    };
    if existing.lines().any(|l| l.trim() == INCLUDE_LINE) {
        return Ok(());
    }
    let mut body = String::new();
    body.push_str("# Added by rig — load generated host aliases\n");
    body.push_str(INCLUDE_LINE);
    body.push('\n');
    if !existing.is_empty() {
        body.push('\n');
        body.push_str(&existing);
        if !existing.ends_with('\n') {
            body.push('\n');
        }
    }
    if let Some(parent) = config_path.parent() {
        fs::create_dir_all(parent).map_err(RigError::Io)?;
    }
    fs::write(config_path, body).map_err(RigError::Io)?;
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let _ = fs::set_permissions(config_path, fs::Permissions::from_mode(0o600));
    }
    Ok(())
}
