#!/usr/bin/env bash
# Start all inventory nodes with Apple `container` for multi-host rig smoke.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
RIG_ROOT="$(cd "${ROOT}/../.." && pwd)"
INV="${ROOT}/scripts/lib/inventory.py"
LOCAL_IMAGE="${RIG_APPLE_IMAGE:-local/rig-linux-smoke:latest}"
RUN_SMOKE=0
WITH_PACKAGES=0
FROM_GITHUB=0
GIT_URL="${RIG_GIT_URL:-https://github.com/yamanori99/rig.git}"
DEFAULT_CPUS="${RIG_APPLE_CPUS:-2}"
DEFAULT_MEMORY="${RIG_APPLE_MEMORY:-2048M}"

for arg in "$@"; do
  case "$arg" in
    --smoke) RUN_SMOKE=1 ;;
    --with-packages) WITH_PACKAGES=1 ;;
    --from-github) FROM_GITHUB=1 ;;
    --from-github=*)
      FROM_GITHUB=1
      GIT_URL="${arg#--from-github=}"
      ;;
    -h|--help)
      echo "usage: $0 [--smoke] [--with-packages] [--from-github[=URL]]"
      echo "  Starts every [[node]] in inventory.toml"
      echo "  Mac SSH: ssh -F ${ROOT}/.generated/ssh_config <name>"
      exit 0
      ;;
    *)
      echo "unknown option: $arg" >&2
      exit 1
      ;;
  esac
done

if ! command -v container >/dev/null 2>&1; then
  echo "container CLI not found. Install https://github.com/apple/container" >&2
  exit 1
fi
if [[ "$(uname -s)" != "Darwin" ]] || [[ "$(uname -m)" != "arm64" ]]; then
  echo "testenv/apple-container is macOS Apple silicon only" >&2
  exit 1
fi
if ! command -v python3 >/dev/null 2>&1; then
  echo "python3 is required" >&2
  exit 1
fi

container_ipv4() {
  local name="$1"
  container inspect "${name}" | python3 -c '
import json, sys
data = json.load(sys.stdin)
nets = data[0].get("status", {}).get("networks") or []
if not nets:
    sys.exit(1)
addr = nets[0].get("ipv4Address") or ""
print(addr.split("/")[0])
'
}

write_mac_ssh_config() {
  local gen="${ROOT}/.generated"
  local ctrl="${gen}/controller"
  local kh="${gen}/known_hosts"
  local nodes_json="$1"
  mkdir -p "${gen}"
  umask 077
  {
    echo "# Generated by fleet-up.sh — do not edit"
    echo
    python3 - "${nodes_json}" "${ctrl}" "${kh}" <<'PY'
import json, sys
nodes = json.loads(open(sys.argv[1]).read())
ctrl, kh = sys.argv[2], sys.argv[3]
for n in nodes:
    name, ip = n["name"], n["ip"]
    print(f"Host {name}")
    print(f"  HostName {ip}")
    print("  User dev")
    print("  Port 22")
    print(f"  IdentityFile {ctrl}")
    print("  IdentitiesOnly yes")
    print("  BatchMode yes")
    print("  ConnectTimeout 10")
    print("  StrictHostKeyChecking accept-new")
    print(f"  UserKnownHostsFile {kh}")
    print("  ServerAliveInterval 60")
    print("  ServerAliveCountMax 10")
    print("  TCPKeepAlive yes")
    print()
PY
  } > "${gen}/ssh_config"
}

inject_client_key() {
  local name="$1"
  local cfg="${ROOT}/.generated/ssh_config"
  local key="${ROOT}/.generated/client"
  ssh -F "${cfg}" "${name}" "mkdir -p ~/.ssh && chmod 700 ~/.ssh"
  scp -F "${cfg}" -q "${key}" "${name}:.ssh/id_ed25519"
  scp -F "${cfg}" -q "${key}.pub" "${name}:.ssh/id_ed25519.pub"
  ssh -F "${cfg}" "${name}" "chmod 600 ~/.ssh/id_ed25519 ~/.ssh/id_ed25519.pub"
}

echo "Starting container system (no-op if already up)..."
container system start

"${ROOT}/scripts/gen-keys.sh"

echo "Building ${LOCAL_IMAGE}..."
(cd "${ROOT}" && container build -t "${LOCAL_IMAGE}" .)

"${ROOT}/scripts/fleet-down.sh"

MOUNT_KEYS="type=bind,source=${ROOT}/mounted-keys,target=/mounted-keys,readonly"

if [[ "${FROM_GITHUB}" -eq 0 ]]; then
  echo "Mode: bind-mount ${RIG_ROOT} → /home/dev/rig"
else
  echo "Mode: guests will git clone ${GIT_URL}"
fi

echo "Creating fleet from inventory.toml..."
while IFS=$'\t' read -r name role; do
  [[ -n "${name}" ]] || continue
  CREATE_ARGS=(
    create -d --name "${name}" --network default
    -c "${DEFAULT_CPUS}" -m "${DEFAULT_MEMORY}"
    -u root
    --mount "${MOUNT_KEYS}"
  )
  if [[ "${FROM_GITHUB}" -eq 0 ]]; then
    CREATE_ARGS+=(--mount "type=bind,source=${RIG_ROOT},target=/home/dev/rig")
  fi
  echo "  + ${name} (role=${role})"
  container "${CREATE_ARGS[@]}" "${LOCAL_IMAGE}"
  container start "${name}"
done < <(python3 "${INV}" tsv)

echo "Waiting for IPv4 on all nodes..."
RUNTIME_JSON="[]"
while IFS=$'\t' read -r name role; do
  [[ -n "${name}" ]] || continue
  IP=""
  for ((i = 1; i <= 40; i++)); do
    IP="$(container_ipv4 "${name}" 2>/dev/null || true)"
    if [[ -n "${IP}" ]]; then
      break
    fi
    sleep 1
  done
  if [[ -z "${IP}" ]]; then
    echo "no IPv4 for ${name}" >&2
    container ls >&2
    exit 1
  fi
  echo "  ${name} → ${IP}:22"
  RUNTIME_JSON="$(
    NAME="${name}" ROLE="${role}" IP="${IP}" RUNTIME_JSON="${RUNTIME_JSON}" python3 - <<'PY'
import json, os
nodes = json.loads(os.environ["RUNTIME_JSON"])
nodes.append({
    "name": os.environ["NAME"],
    "role": os.environ["ROLE"],
    "ip": os.environ["IP"],
    "user": "dev",
})
print(json.dumps(nodes))
PY
  )"
done < <(python3 "${INV}" tsv)

GEN="${ROOT}/.generated"
mkdir -p "${GEN}"
printf '%s\n' "${RUNTIME_JSON}" > "${GEN}/nodes.json"
write_mac_ssh_config "${GEN}/nodes.json"
CFG="${GEN}/ssh_config"
echo "Mac SSH config → ${CFG}"

echo "Waiting for sshd on all nodes..."
while IFS=$'\t' read -r name role; do
  [[ -n "${name}" ]] || continue
  ok=0
  for ((i = 1; i <= 40; i++)); do
    if ssh -F "${CFG}" "${name}" "echo ok" >/dev/null 2>&1; then
      ok=1
      break
    fi
    sleep 1
  done
  if [[ "${ok}" -ne 1 ]]; then
    echo "sshd not ready on ${name}" >&2
    exit 1
  fi
done < <(python3 "${INV}" tsv)

echo "Injecting client SSH key on workstation nodes..."
while IFS=$'\t' read -r name role; do
  [[ -n "${name}" ]] || continue
  if [[ "${role}" == "workstation" ]]; then
    inject_client_key "${name}"
    echo "  client key → ${name}"
  fi
done < <(python3 "${INV}" tsv)

if [[ "${RUN_SMOKE}" -eq 1 ]]; then
  export RIG_APPLE_WITH_PACKAGES="${WITH_PACKAGES}"
  export RIG_APPLE_FROM_GITHUB="${FROM_GITHUB}"
  export RIG_GIT_URL="${GIT_URL}"
  "${ROOT}/scripts/fleet-smoke.sh"
fi

echo "Fleet up. Example: ssh -F ${CFG} rig-ws"
